name:                Implementation
version:             0.1.0.0
github:              "githubuser/Implementation"
license:             BSD3
author:              "Kazuki Watanabe"
maintainer:          "kazukiwatanabe@nii.ac.jp"
copyright:           "2022 Kazuki Watanabe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Implementation#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- transformers
- containers
- split 
- random
- vector 
- bytestring
- text
- timeit
- criterion

library:
  source-dirs: src

executables:
  Implementation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Implementation

tests:
  Implementation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Implementation
